tap 'git-duet/tap'
tap 'pivotal/tap'
tap 'vmware-tanzu/carvel'
tap 'cloudfoundry/tap'

brew 'cloudfoundry/tap/bosh-cli'

brew 'bash-completion'
brew 'coreutils'
brew 'direnv'
brew 'git'
brew 'git-duet'
brew 'go'
brew 'htop'
brew 'jq'
brew 'lastpass-cli'
brew 'postgresql'
brew 'pstree'
brew 'python3'
brew 's3cmd'
brew 'shellcheck'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'yq'
brew 'z'

# Replace Darwin utilities with GNU for compatibility with Linux
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnutls'
brew 'ed'
brew 'findutils'
brew 'grep'

cask 'docker'
cask 'flycut'
cask 'goland'
cask 'google-cloud-sdk'
cask 'istat-menus'
cask 'iterm2'

# k8s tools
brew 'helm'
brew 'hyperkit'
brew 'kubebuilder'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'minikube'
brew 'kustomize'
brew 'kubebuilder'
brew 'minio/stable/mc'
brew 'stern'

# Carvel tools
brew 'ytt'
brew 'kbld'
brew 'kapp'
brew 'imgpkg'
brew 'kwt'
brew 'vendir'
